CREATE TABLE AYUDA 
(
  ANYO DATE NOT NULL 
, PARCELA VARCHAR2(20) NOT NULL 
, EXTENSION VARCHAR2(20) 
, TIPOAYUDA VARCHAR2(20) 
, CANTIDAD VARCHAR2(20) 
, CONSTRAINT AYUDA_PK PRIMARY KEY 
  (
    ANYO 
  , PARCELA 
  )
  ENABLE 
);

CREATE TABLE PARCELA 
(
  COD_PARCELA VARCHAR2(20) NOT NULL 
, PROPIETARIO VARCHAR2(20) NOT NULL 
, REGADIO VARCHAR2(1) 
, EXTENSION VARCHAR2(20) 
, CONSTRAINT PARCELA_PK PRIMARY KEY 
  (
    COD_PARCELA 
  )
  ENABLE 
);

CREATE TABLE POZO 
(
  CODPOZO NUMBER NOT NULL 
, PARCELA VARCHAR2(20) NOT NULL 
, PROFUNDIDAD VARCHAR2(20) 
, CAUDAL VARCHAR2(20) 
, REGADIO VARCHAR2(20) 
, CONSTRAINT POZO_PK PRIMARY KEY 
  (
    CODPOZO 
  )
  ENABLE 
);

CREATE TABLE PROPIETARIOS 
(
  DNI VARCHAR2(20) NOT NULL 
, POBLACION VARCHAR2(20) 
, NOMBRE VARCHAR2(20) 
, TELEFONO VARCHAR2(20) 
, CODPOSTAL VARCHAR2(20) 
, DIRECCION VARCHAR2(20) 
, CONSTRAINT PROPIETARIOS_PK PRIMARY KEY 
  (
    DNI 
  )
  ENABLE 
);

ALTER TABLE AYUDA
ADD CONSTRAINT AYUDA_FK1 FOREIGN KEY
(
  PARCELA 
)
REFERENCES PARCELA
(
  COD_PARCELA 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE PARCELA
ADD CONSTRAINT PARCELA_FK1 FOREIGN KEY
(
  PROPIETARIO 
)
REFERENCES PROPIETARIOS
(
  DNI 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE POZO
ADD CONSTRAINT POZO_FK1 FOREIGN KEY
(
  PARCELA 
)
REFERENCES PARCELA
(
  COD_PARCELA 
)
ON DELETE CASCADE ENABLE;
