
package client;

/**
 *
 * @author carlos
 */
public class Frame extends javax.swing.JFrame {


    boolean aparezco;
    int contador;
    final int limite=5;
    
    /** Creates new form Frame */
    public Frame() {
        aparezco=true;
        contador=1;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        botonPulsar = new javax.swing.JButton();
        botonAparezco = new javax.swing.JButton();
        cuadroTexto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonPulsar.setText("Pulsar");
        botonPulsar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPulsarActionPerformed(evt);
            }
        });

        botonAparezco.setText("Aparezco");
        botonAparezco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAparezcoActionPerformed(evt);
            }
        });

        cuadroTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadroTextoActionPerformed(evt);
            }
        });
        cuadroTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cuadroTextoKeyTyped(evt);
            }
        });

        jLabel1.setText("Introduzca su nombre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(botonPulsar)
                        .addGap(110, 110, 110)
                        .addComponent(botonAparezco))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(cuadroTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonPulsar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAparezco, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cuadroTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        pack();
    }//GEN-END:initComponents

    private void botonAparezcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAparezcoActionPerformed
        contador=1;
        aparezco=true;
        botonPulsar.setEnabled(true);
        botonPulsar.setText("Pulsar");
        cuadroTexto.setText("");
    }//GEN-LAST:event_botonAparezcoActionPerformed

    private void botonPulsarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPulsarActionPerformed
        //Se trata de un asignacion de cambio de estado
        aparezco=!aparezco;
        botonAparezco.setVisible(aparezco);
    }//GEN-LAST:event_botonPulsarActionPerformed

    private void cuadroTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadroTextoActionPerformed

        String texto=cuadroTexto.getText();
        texto= texto +" "+contador+" veces";
        botonPulsar.setText(texto);
        if (contador==limite){
            botonPulsar.setEnabled(false);
        }
        contador++;
    }//GEN-LAST:event_cuadroTextoActionPerformed

    private void cuadroTextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cuadroTextoKeyTyped
        String texto=cuadroTexto.getText();
        texto= texto +" "+contador+" veces";
        botonPulsar.setText(texto);
        if (contador==limite){
            botonPulsar.setEnabled(false);
        }
        contador++;
    }//GEN-LAST:event_cuadroTextoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAparezco;
    private javax.swing.JButton botonPulsar;
    private javax.swing.JTextField cuadroTexto;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
