
package client;

import java.awt.Dimension;

import java.util.List;
import javax.swing.*;

/**
 *
 * @author carlos
 */
public class Frame extends javax.swing.JFrame {


    boolean aparezco;
    int contador;
    final int limite=5;
    
    /** Creates new form Frame */
    public Frame() {
        aparezco=true;
        contador=1;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        bGBotonesRadio = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        bgMenu = new javax.swing.ButtonGroup();
        panelRadioBoton = new javax.swing.JPanel();
        rBBajo = new javax.swing.JRadioButton();
        rBMedio = new javax.swing.JRadioButton();
        rBAlto = new javax.swing.JRadioButton();
        listaColores = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        etiCombo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaNombres = new javax.swing.JList();
        etiSeleccMulti = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        bLimpiar = new javax.swing.JButton();
        bDialogo = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuLAF = new javax.swing.JMenu();
        LAFMetal = new javax.swing.JCheckBoxMenuItem();
        LAFBasic = new javax.swing.JCheckBoxMenuItem();
        LAFMulti = new javax.swing.JCheckBoxMenuItem();
        LAFNimbus = new javax.swing.JCheckBoxMenuItem();
        LAFInstalled = new javax.swing.JCheckBoxMenuItem();

        bGBotonesRadio.add(rBAlto);
        bGBotonesRadio.add(rBMedio);
        bGBotonesRadio.add(rBBajo);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        bgMenu.add(LAFMetal);
        bgMenu.add(LAFBasic);
        bgMenu.add(LAFMulti);
        bgMenu.add(LAFNimbus);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelRadioBoton.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Grupo de Botones Radio", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Abyssinica SIL", 1, 10))); // NOI18N
        panelRadioBoton.setToolTipText("Seleccione radio");

        rBBajo.setText("Bajo");
        rBBajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBBajoActionPerformed(evt);
            }
        });

        rBMedio.setText("Medio");
        rBMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBMedioActionPerformed(evt);
            }
        });

        rBAlto.setText("Alto");
        rBAlto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRadioBotonLayout = new javax.swing.GroupLayout(panelRadioBoton);
        panelRadioBoton.setLayout(panelRadioBotonLayout);
        panelRadioBotonLayout.setHorizontalGroup(
            panelRadioBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRadioBotonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rBAlto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rBBajo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rBMedio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRadioBotonLayout.setVerticalGroup(
            panelRadioBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRadioBotonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelRadioBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rBAlto)
                    .addComponent(rBBajo)
                    .addComponent(rBMedio))
                .addGap(49, 49, 49))
        );

        listaColores.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escriba o Seleccione un color", "Rojo", "Amarillo", "Azul", "Verde", "Blanco" }));
        listaColores.setToolTipText("Seleccione Combo");
        listaColores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaColoresActionPerformed(evt);
            }
        });

        etiCombo.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        etiCombo.setText("Lista de Botones Desplegable");

        listaNombres.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Macarena Ureña", "Carlos Rodríguez López", "Juan Ureña", "Amalia López", "Elvis Preisler" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listaNombres.setToolTipText("esa lista guapa");
        listaNombres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                listaNombresMouseExited(evt);
            }
        });
        jScrollPane2.setViewportView(listaNombres);

        etiSeleccMulti.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        etiSeleccMulti.setText("Lista de Selección Multiple");

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Area de Texto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Abyssinica SIL", 1, 10))); // NOI18N

        textArea.setColumns(20);
        textArea.setRows(5);
        textArea.setToolTipText("Escribe aquí lo que le plazca");
        jScrollPane3.setViewportView(textArea);

        bLimpiar.setText("Limpiar");
        bLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarActionPerformed(evt);
            }
        });

        bDialogo.setText("Diálogo");
        bDialogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDialogoActionPerformed(evt);
            }
        });

        menuLAF.setText("Look&Feel");

        LAFMetal.setSelected(true);
        LAFMetal.setText("Metal");
        LAFMetal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAFMetalActionPerformed(evt);
            }
        });
        menuLAF.add(LAFMetal);

        LAFBasic.setText("Basic");
        LAFBasic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAFBasicActionPerformed(evt);
            }
        });
        menuLAF.add(LAFBasic);

        LAFMulti.setText("Multi");
        LAFMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAFMultiActionPerformed(evt);
            }
        });
        menuLAF.add(LAFMulti);

        LAFNimbus.setText("Nimbus");
        LAFNimbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAFNimbusActionPerformed(evt);
            }
        });
        menuLAF.add(LAFNimbus);

        LAFInstalled.setText("ver LAF instalados");
        LAFInstalled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAFInstalledActionPerformed(evt);
            }
        });
        menuLAF.add(LAFInstalled);

        jMenuBar1.add(menuLAF);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelRadioBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiCombo)
                            .addComponent(listaColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(etiSeleccMulti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))))
                .addContainerGap())
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bDialogo))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRadioBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiCombo)
                    .addComponent(etiSeleccMulti))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listaColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bLimpiar)
                    .addComponent(bDialogo))
                .addGap(30, 30, 30))
        );

        pack();
    }//GEN-END:initComponents

    private void rbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbActionPerformed
            // TODO add your handling code here:
        this.textArea.append("Has seleccionado el radio buton"+ ((JRadioButton) evt.getSource()).getText() + "\n" );
    }//GEN-LAST:event_rbActionPerformed

    private void listaColoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaColoresActionPerformed
        // TODO add your handling code here:
        if (listaColores.getSelectedItem()==0){
            this.textArea.append("No se ha seleccionado ningun elemento de la lista desplegable es \n");
        } else {
            this.textArea.append("El elemento seleccionado de la lista desplegable es \n");
            this.textArea.append("indice:"+  listaColores.getSelectedIndex() + " - color:"+ listaColores.getSelectedItem()+ "\n");
        }
    }//GEN-LAST:event_listaColoresActionPerformed

    private void bLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarActionPerformed
        // TODO add your handling code here:
        this.textArea.setText("");
    }//GEN-LAST:event_bLimpiarActionPerformed

    private void bDialogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDialogoActionPerformed
        // TODO add your handling code here:
        String val = JOptionPane.showInputDialog(this, "¿Cuantos dedeos ves aqui?", "Caja Diálogo", JOptionPane.QUESTION_MESSAGE);
        if (val!=null&&!val.equals("")){
            this.textArea.append("Has introducido el valor" + val + "en el cuadro de dialogo");
        }else{
            this.textArea.append("No has introducido valor en el cuadro de dialogo");
        }
        
    }//GEN-LAST:event_bDialogoActionPerformed

    private void LAFBasicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAFBasicActionPerformed
        // TODO add your handling code here:
        try {
            UIManager.setLookAndFeel("javax.swing.plaf.basic.BasicLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception e) {
            this.textArea.append(e.toString());
        }
    }//GEN-LAST:event_LAFBasicActionPerformed

    private void LAFInstalledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAFInstalledActionPerformed
        // TODO add your handling code here:
        UIManager.LookAndFeelInfo[] lafs = UIManager.getInstalledLookAndFeels();
        String[] columnas = {"Nombre","Clase"};
        Object[][] datosLafs = new Object [5][2];
        int i=0;
        
        for (UIManager.LookAndFeelInfo laf: lafs){
            datosLafs[i][0] = laf.getName();
            datosLafs[i][1] = laf.getClassName();
            i++;
        }
        
        JTable tabla = new JTable (datosLafs,columnas);
        
        /*Indica el tamaño de las columnas a la hora de mostrarlas*/
        tabla.getColumnModel().getColumn(0).setPreferredWidth(120);
        tabla.getColumnModel().getColumn(1).setPreferredWidth(380);
        /*Se se pone directamente la tabla de JOptionPane, no muestra los ordenes de la columnas por lo que optamos por
         *lo que optamos por ponerlo en JScroll Panel*/
        JScrollPane panel = new JScrollPane(tabla);
        panel.setPreferredSize(new Dimension (500, 110));
        
        JOptionPane.showMessageDialog(this, panel, "Tipos de Look and Feel Instalados", JOptionPane.INFORMATION_MESSAGE);
        
        
    }//GEN-LAST:event_LAFInstalledActionPerformed

    private void LAFMetalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAFMetalActionPerformed
        // TODO add your handling code here:
        try {
            UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception e) {
            this.textArea.append(e.toString());
        }
    }//GEN-LAST:event_LAFMetalActionPerformed

    private void LAFMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAFMultiActionPerformed
        // TODO add your handling code here:
        try {
            UIManager.setLookAndFeel("javax.swing.plaf.multi.MultiLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception e) {
            this.textArea.append(e.toString());
        }
    }//GEN-LAST:event_LAFMultiActionPerformed

    private void LAFNimbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAFNimbusActionPerformed
        // TODO add your handling code here:
        try {
            UIManager.setLookAndFeel("javax.swing.plaf.nimbus.MultiLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception e) {
            this.textArea.append(e.toString());
        }
    }//GEN-LAST:event_LAFNimbusActionPerformed

    private void rBBajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBBajoActionPerformed
        // TODO add your handling code here:
        this.textArea.append("Has seleccionado el radio buton"+ ((JRadioButton) evt.getSource()).getText() + "\n" );
    }//GEN-LAST:event_rBBajoActionPerformed

    private void rBMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBMedioActionPerformed
        // TODO add your handling code here:
        this.textArea.append("Has seleccionado el radio buton"+ ((JRadioButton) evt.getSource()).getText() + "\n" );
    }//GEN-LAST:event_rBMedioActionPerformed

    private void listaNombresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaNombresMouseExited
        // TODO add your handling code here:
        List <String> items = this.listaNombres.getSelectedValuesList();
        if (items.size()==0){
            this.textArea.append("No se ha seleccionado ningun elemento de la lista de seleccion multiple de nombres\n");
        }else{
            this.textArea.append("Los elementos seleccionados de la lista de seleccion multiple de nombres son\n");
            for (int i=0;i<items.size(); i++){
                this.textArea.append("\t"+ (items).get(i) + "\n");
            }
        }
    }//GEN-LAST:event_listaNombresMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem LAFBasic;
    private javax.swing.JCheckBoxMenuItem LAFInstalled;
    private javax.swing.JCheckBoxMenuItem LAFMetal;
    private javax.swing.JCheckBoxMenuItem LAFMulti;
    private javax.swing.JCheckBoxMenuItem LAFNimbus;
    private javax.swing.JButton bDialogo;
    private javax.swing.ButtonGroup bGBotonesRadio;
    private javax.swing.JButton bLimpiar;
    private javax.swing.ButtonGroup bgMenu;
    private javax.swing.JLabel etiCombo;
    private javax.swing.JLabel etiSeleccMulti;
    private javax.swing.JList jList1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox listaColores;
    private javax.swing.JList listaNombres;
    private javax.swing.JMenu menuLAF;
    private javax.swing.JPanel panelRadioBoton;
    private javax.swing.JRadioButton rBAlto;
    private javax.swing.JRadioButton rBBajo;
    private javax.swing.JRadioButton rBMedio;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables

}
